### PR TITLE
Fixed Status Plugin

### PR DESCRIPTION
**Pull request by tanndlin**
Changed it so that it parses the GitHub website for data, that way it works in Docker

### CODE REVIEW

**Review by c650 — COMMENTED** [review]
but the latest commit on github is not necessarily what the bot is running ..?

**Comment by tanndlin** [comment]
Not necessarily, but usually. I'm not sure what I can do, code-wise, to make it work inside of docker. I think that's something you would have to fiddle around with to get the old code working.

**Comment by tanndlin** [comment]
Oh! What we could do, is get all this info on startup. And just spit it out on `!status` call. It still, wont be *necessarily* what the bot is running, but how often does the bot really reset without taking on the latest commit?

**Comment by c650** [comment]
There’s a way to do it when you build the docker image. That’s probably the best route

**Comment by tanndlin** [comment]
Is that something I need to do? I'm not sure how to go about that.

**Comment by tanndlin** [comment]
I'm lost on how to do it through docker, should I close this PR for now?

**Comment by c650** [comment]
Sure yeah no worries

**Comment by tanndlin** [comment]
Closing until I find a solution

**Pull request closed without merging**
