### PR TITLE
prevent !register ALL from working

### PR DESCRIPTION
**Pull request by Kurtoid**

### CODE REVIEW

**Comment by joey-colon** [comment]
thanks for reporting!

i believe we should transform args to lowercase before running the plugin which is located [here](https://github.com/joey-colon/lion/blob/master/src/app/handlers/command.handler.ts#L50)

**Comment by Kurtoid** [comment]
Would converting to lowercase there break anything else?

**Comment by c650** [comment]
yes

**Comment by c650** [comment]
There are a handful of plugins that take a username as one of the arguments, which is case sensitive

**Review by c650 — APPROVED** [review]
lgtm

**Pull request merged**
